// <auto-generated />
using DotNetConfDemo1.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetConfDemo1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180818104914_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("DotNetConfDemo1.Model.Country", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new { Id = 1, Name = "Afghanistan" },
                        new { Id = 2, Name = "Albania" },
                        new { Id = 3, Name = "Algeria" },
                        new { Id = 4, Name = "Andorra" },
                        new { Id = 5, Name = "Angola" },
                        new { Id = 6, Name = "Antigua and Barbuda" },
                        new { Id = 7, Name = "Argentina" },
                        new { Id = 8, Name = "Armenia" },
                        new { Id = 9, Name = "Australia" },
                        new { Id = 10, Name = "Austria" },
                        new { Id = 11, Name = "Azerbaijan" },
                        new { Id = 12, Name = "Bahamas" },
                        new { Id = 13, Name = "Bahrain" },
                        new { Id = 14, Name = "Bangladesh" },
                        new { Id = 15, Name = "Barbados" },
                        new { Id = 16, Name = "Belarus" },
                        new { Id = 17, Name = "Belgium" },
                        new { Id = 18, Name = "Belize" },
                        new { Id = 19, Name = "Benin" },
                        new { Id = 20, Name = "Bhutan" },
                        new { Id = 21, Name = "Bolivia (Plurinational State of)" },
                        new { Id = 22, Name = "Bosnia and Herzegovina" },
                        new { Id = 23, Name = "Botswana" },
                        new { Id = 24, Name = "Brazil" },
                        new { Id = 25, Name = "Brunei Darussalam" },
                        new { Id = 26, Name = "Bulgaria" },
                        new { Id = 27, Name = "Burkina Faso" },
                        new { Id = 28, Name = "Burundi" },
                        new { Id = 29, Name = "Cambodia" },
                        new { Id = 30, Name = "Cameroon" },
                        new { Id = 31, Name = "Canada" },
                        new { Id = 32, Name = "Cape Verde" },
                        new { Id = 33, Name = "Central African Republic" },
                        new { Id = 34, Name = "Chad" },
                        new { Id = 35, Name = "Chile" },
                        new { Id = 36, Name = "China" },
                        new { Id = 37, Name = "Colombia" },
                        new { Id = 38, Name = "Comoros" },
                        new { Id = 39, Name = "Congo" },
                        new { Id = 40, Name = "Costa Rica" },
                        new { Id = 41, Name = "Côte d'Ivoire" },
                        new { Id = 42, Name = "Croatia" },
                        new { Id = 43, Name = "Cuba" },
                        new { Id = 44, Name = "Cyprus" },
                        new { Id = 45, Name = "Czech Republic" },
                        new { Id = 46, Name = "Democratic People's Republic of Korea" },
                        new { Id = 47, Name = "Democratic Republic of the Congo" },
                        new { Id = 48, Name = "Denmark" },
                        new { Id = 49, Name = "Djibouti" },
                        new { Id = 50, Name = "Dominica" },
                        new { Id = 51, Name = "Dominican Republic" },
                        new { Id = 52, Name = "Ecuador" },
                        new { Id = 53, Name = "Egypt" },
                        new { Id = 54, Name = "El Salvador" },
                        new { Id = 55, Name = "Equatorial Guinea" },
                        new { Id = 56, Name = "Eritrea" },
                        new { Id = 57, Name = "Estonia" },
                        new { Id = 58, Name = "Ethiopia" },
                        new { Id = 59, Name = "Fiji" },
                        new { Id = 60, Name = "Finland" },
                        new { Id = 61, Name = "France" },
                        new { Id = 62, Name = "Gabon" },
                        new { Id = 63, Name = "Gambia" },
                        new { Id = 64, Name = "Georgia" },
                        new { Id = 65, Name = "Germany" },
                        new { Id = 66, Name = "Ghana" },
                        new { Id = 67, Name = "Greece" },
                        new { Id = 68, Name = "Grenada" },
                        new { Id = 69, Name = "Guatemala" },
                        new { Id = 70, Name = "Guinea" },
                        new { Id = 71, Name = "Guinea-Bissau" },
                        new { Id = 72, Name = "Guyana" },
                        new { Id = 73, Name = "Haiti" },
                        new { Id = 74, Name = "Honduras" },
                        new { Id = 75, Name = "Hungary" },
                        new { Id = 76, Name = "Iceland" },
                        new { Id = 77, Name = "India" },
                        new { Id = 78, Name = "Indonesia" },
                        new { Id = 79, Name = "Iran (Islamic Republic of)" },
                        new { Id = 80, Name = "Iraq" },
                        new { Id = 81, Name = "Ireland" },
                        new { Id = 82, Name = "Israel" },
                        new { Id = 83, Name = "Italy" },
                        new { Id = 84, Name = "Jamaica" },
                        new { Id = 85, Name = "Japan" },
                        new { Id = 86, Name = "Jordan" },
                        new { Id = 87, Name = "Kazakhstan" },
                        new { Id = 88, Name = "Kenya" },
                        new { Id = 89, Name = "Kiribati" },
                        new { Id = 90, Name = "Kuwait" },
                        new { Id = 91, Name = "Kyrgyzstan" },
                        new { Id = 92, Name = "Lao People's Democratic Republic" },
                        new { Id = 93, Name = "Latvia" },
                        new { Id = 94, Name = "Lebanon" },
                        new { Id = 95, Name = "Lesotho" },
                        new { Id = 96, Name = "Liberia" },
                        new { Id = 97, Name = "Libyan Arab Jamahiriya" },
                        new { Id = 98, Name = "Liechtenstein" },
                        new { Id = 99, Name = "Lithuania" },
                        new { Id = 100, Name = "Luxembourg" },
                        new { Id = 101, Name = "Madagascar" },
                        new { Id = 102, Name = "Malawi" },
                        new { Id = 103, Name = "Malaysia" },
                        new { Id = 104, Name = "Maldives" },
                        new { Id = 105, Name = "Mali" },
                        new { Id = 106, Name = "Malta" },
                        new { Id = 107, Name = "Marshall Islands" },
                        new { Id = 108, Name = "Mauritania" },
                        new { Id = 109, Name = "Mauritius" },
                        new { Id = 110, Name = "Mexico" },
                        new { Id = 111, Name = "Micronesia (Federated States of)" },
                        new { Id = 112, Name = "Monaco" },
                        new { Id = 113, Name = "Mongolia" },
                        new { Id = 114, Name = "Montenegro" },
                        new { Id = 115, Name = "Morocco" },
                        new { Id = 116, Name = "Mozambique" },
                        new { Id = 117, Name = "Myanmar" },
                        new { Id = 118, Name = "Namibia" },
                        new { Id = 119, Name = "Nauru" },
                        new { Id = 120, Name = "Nepal" },
                        new { Id = 121, Name = "Netherlands" },
                        new { Id = 122, Name = "New Zealand" },
                        new { Id = 123, Name = "Nicaragua" },
                        new { Id = 124, Name = "Niger" },
                        new { Id = 125, Name = "Nigeria" },
                        new { Id = 126, Name = "Norway" },
                        new { Id = 127, Name = "Oman" },
                        new { Id = 128, Name = "Pakistan" },
                        new { Id = 129, Name = "Palau" },
                        new { Id = 130, Name = "Panama" },
                        new { Id = 131, Name = "Papua New Guinea" },
                        new { Id = 132, Name = "Paraguay" },
                        new { Id = 133, Name = "Peru" },
                        new { Id = 134, Name = "Philippines" },
                        new { Id = 135, Name = "Poland" },
                        new { Id = 136, Name = "Portugal" },
                        new { Id = 137, Name = "Qatar" },
                        new { Id = 138, Name = "Republic of Korea" },
                        new { Id = 139, Name = "Republic of Moldova" },
                        new { Id = 140, Name = "Romania" },
                        new { Id = 141, Name = "Russian Federation" },
                        new { Id = 142, Name = "Rwanda" },
                        new { Id = 143, Name = "Saint Kitts and Nevis" },
                        new { Id = 144, Name = "Saint Lucia" },
                        new { Id = 145, Name = "Saint Vincent and the Grenadines" },
                        new { Id = 146, Name = "Samoa" },
                        new { Id = 147, Name = "San Marino" },
                        new { Id = 148, Name = "Sao Tome and Principe" },
                        new { Id = 149, Name = "Saudi Arabia" },
                        new { Id = 150, Name = "Senegal" },
                        new { Id = 151, Name = "Serbia" },
                        new { Id = 152, Name = "Seychelles" },
                        new { Id = 153, Name = "Sierra Leone" },
                        new { Id = 154, Name = "Singapore" },
                        new { Id = 155, Name = "Slovakia" },
                        new { Id = 156, Name = "Slovenia" },
                        new { Id = 157, Name = "Solomon Islands" },
                        new { Id = 158, Name = "Somalia" },
                        new { Id = 159, Name = "South Africa" },
                        new { Id = 160, Name = "South Sudan" },
                        new { Id = 161, Name = "Spain" },
                        new { Id = 162, Name = "Sri Lanka" },
                        new { Id = 163, Name = "Sudan" },
                        new { Id = 164, Name = "Suriname" },
                        new { Id = 165, Name = "Swaziland" },
                        new { Id = 166, Name = "Sweden" },
                        new { Id = 167, Name = "Switzerland" },
                        new { Id = 168, Name = "Syrian Arab Republic" },
                        new { Id = 169, Name = "Tajikistan" },
                        new { Id = 170, Name = "Thailand" },
                        new { Id = 171, Name = "The former Yugoslav Republic of Macedonia" },
                        new { Id = 172, Name = "Timor-Leste" },
                        new { Id = 173, Name = "Togo" },
                        new { Id = 174, Name = "Tonga" },
                        new { Id = 175, Name = "Trinidad and Tobago" },
                        new { Id = 176, Name = "Tunisia" },
                        new { Id = 177, Name = "Turkey" },
                        new { Id = 178, Name = "Turkmenistan" },
                        new { Id = 179, Name = "Tuvalu" },
                        new { Id = 180, Name = "Uganda" },
                        new { Id = 181, Name = "Ukraine" },
                        new { Id = 182, Name = "United Arab Emirates" },
                        new { Id = 183, Name = "United Kingdom of Great Britain and Northern Ireland" },
                        new { Id = 184, Name = "United Republic of Tanzania" },
                        new { Id = 185, Name = "United States of America" },
                        new { Id = 186, Name = "Uruguay" },
                        new { Id = 187, Name = "Uzbekistan" },
                        new { Id = 188, Name = "Vanuatu" },
                        new { Id = 189, Name = "Venezuela (Bolivarian Republic of)" },
                        new { Id = 190, Name = "Viet Nam" },
                        new { Id = 191, Name = "Yemen" },
                        new { Id = 192, Name = "Zambia" },
                        new { Id = 193, Name = "Zimbabwe" }
                    );
                });

            modelBuilder.Entity("DotNetConfDemo1.Model.State", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("CountryId");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("States");

                    b.HasData(
                        new { Id = 1, CountryId = 185, Name = "Alabama" },
                        new { Id = 2, CountryId = 185, Name = "Alaska" },
                        new { Id = 3, CountryId = 185, Name = "Arizona" },
                        new { Id = 4, CountryId = 185, Name = "Arkansas" },
                        new { Id = 5, CountryId = 185, Name = "California" },
                        new { Id = 6, CountryId = 185, Name = "Colorado" },
                        new { Id = 7, CountryId = 185, Name = "Connecticut" },
                        new { Id = 8, CountryId = 185, Name = "Delaware" },
                        new { Id = 9, CountryId = 185, Name = "District Of Columbia" },
                        new { Id = 10, CountryId = 185, Name = "Florida" },
                        new { Id = 11, CountryId = 185, Name = "Georgia" },
                        new { Id = 12, CountryId = 185, Name = "Hawaii" },
                        new { Id = 13, CountryId = 185, Name = "Idaho" },
                        new { Id = 14, CountryId = 185, Name = "Illinois" },
                        new { Id = 15, CountryId = 185, Name = "Indiana" },
                        new { Id = 16, CountryId = 185, Name = "Iowa" },
                        new { Id = 17, CountryId = 185, Name = "Kansas" },
                        new { Id = 18, CountryId = 185, Name = "Kentucky" },
                        new { Id = 19, CountryId = 185, Name = "Louisiana" },
                        new { Id = 20, CountryId = 185, Name = "Maine" },
                        new { Id = 21, CountryId = 185, Name = "Maryland" },
                        new { Id = 22, CountryId = 185, Name = "Massachusetts" },
                        new { Id = 23, CountryId = 185, Name = "Michigan" },
                        new { Id = 24, CountryId = 185, Name = "Minnesota" },
                        new { Id = 25, CountryId = 185, Name = "Mississippi" },
                        new { Id = 26, CountryId = 185, Name = "Missouri" },
                        new { Id = 27, CountryId = 185, Name = "Montana" },
                        new { Id = 28, CountryId = 185, Name = "Nebraska" },
                        new { Id = 29, CountryId = 185, Name = "Nevada" },
                        new { Id = 30, CountryId = 185, Name = "New Hampshire" },
                        new { Id = 31, CountryId = 185, Name = "New Jersey" },
                        new { Id = 32, CountryId = 185, Name = "New Mexico" },
                        new { Id = 33, CountryId = 185, Name = "New York" },
                        new { Id = 34, CountryId = 185, Name = "North Carolina" },
                        new { Id = 35, CountryId = 185, Name = "North Dakota" },
                        new { Id = 36, CountryId = 185, Name = "Ohio" },
                        new { Id = 37, CountryId = 185, Name = "Oklahoma" },
                        new { Id = 38, CountryId = 185, Name = "Oregon" },
                        new { Id = 39, CountryId = 185, Name = "Pennsylvania" },
                        new { Id = 40, CountryId = 185, Name = "Rhode Island" },
                        new { Id = 41, CountryId = 185, Name = "South Carolina" },
                        new { Id = 42, CountryId = 185, Name = "South Dakota" },
                        new { Id = 43, CountryId = 185, Name = "Tennessee" },
                        new { Id = 44, CountryId = 185, Name = "Texas" },
                        new { Id = 45, CountryId = 185, Name = "Utah" },
                        new { Id = 46, CountryId = 185, Name = "Vermont" },
                        new { Id = 47, CountryId = 185, Name = "Virginia" },
                        new { Id = 48, CountryId = 185, Name = "Washington" },
                        new { Id = 49, CountryId = 185, Name = "West Virginia" },
                        new { Id = 50, CountryId = 185, Name = "Wisconsin" },
                        new { Id = 51, CountryId = 185, Name = "Wyoming" },
                        new { Id = 52, CountryId = 31, Name = "Alberta" },
                        new { Id = 53, CountryId = 31, Name = "British Columbia" },
                        new { Id = 54, CountryId = 31, Name = "Manitoba" },
                        new { Id = 55, CountryId = 31, Name = "New Brunswick" },
                        new { Id = 56, CountryId = 31, Name = "Newfoundland and Labrador" },
                        new { Id = 57, CountryId = 31, Name = "Nova Scotia" },
                        new { Id = 58, CountryId = 31, Name = "Northwest Territories" },
                        new { Id = 59, CountryId = 31, Name = "Nunavut" },
                        new { Id = 60, CountryId = 31, Name = "Ontario" },
                        new { Id = 61, CountryId = 31, Name = "Prince Edward Island" },
                        new { Id = 62, CountryId = 31, Name = "Quebec" },
                        new { Id = 63, CountryId = 31, Name = "Saskatchewan" },
                        new { Id = 64, CountryId = 31, Name = "Yukon" }
                    );
                });

            modelBuilder.Entity("DotNetConfDemo1.Model.State", b =>
                {
                    b.HasOne("DotNetConfDemo1.Model.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
